# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
