# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_edition_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='book',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='books.Book'),
            preserve_default=False,
        ),
    ]
